"""
Young Life Crowd Counter API
FastAPI application to count people in uploaded images 
and return the image with numbered detections.
"""

from fastapi import FastAPI, UploadFile, File, BackgroundTasks
from fastapi.responses import FileResponse, JSONResponse
from crowd_counter import CrowdCounter
import shutil
import os
import uuid
from pathlib import Path

app = FastAPI(title="Young Life Crowd Counter API")

# Global counter instance
counter = None

TEMP_DIR = Path("temp_uploads")
TEMP_DIR.mkdir(exist_ok=True)

RESULTS_DIR = Path("results")
RESULTS_DIR.mkdir(exist_ok=True)

@app.on_event("startup")
async def startup_event():
    global counter
    print("🚀 Initializing Crowd Counter Model...")
    # Use the optimized settings: confidence=0.05
    # Note: imgsz is passed during inference in count()
    counter = CrowdCounter(confidence=0.08, model_path="weights/yolov8n-head.pt")
    print("✅ Model loaded and ready!")

@app.get("/")
def read_root():
    return {
        "message": "Young Life Crowd Counter API is running.",
        "endpoints": [
            "POST /predict/count (Count only)",
            "POST /predict/gender (Count + Gender)",
            "POST /count (Legacy: Count + Gender)"
        ]
    }

def cleanup_file(path: str):
    """Delete a file in the background"""
    try:
        if os.path.exists(path):
            os.remove(path)
    except Exception as e:
        print(f"Error cleaning up {path}: {e}")

async def process_image_counting(file: UploadFile, background_tasks: BackgroundTasks, predict_gender: bool):
    """
    Helper function to process image upload and counting
    """
    if not counter:
        return JSONResponse(status_code=500, content={"error": "Model not initialized"})

    # Generate unique ID for this request to avoid collisions
    request_id = str(uuid.uuid4())
    input_filename = f"{request_id}_{file.filename}"
    input_path = TEMP_DIR / input_filename
    
    # Save uploaded file
    with open(input_path, "wb") as buffer:
        shutil.copyfileobj(file.file, buffer)
    
    try:
        # Run counting
        result = counter.count(
            str(input_path), 
            save_result=True, 
            output_dir=str(RESULTS_DIR),
            imgsz=3008,
            predict_gender=predict_gender
        )
        
        # Determine the output path generated by CrowdCounter
        stem = Path(input_filename).stem
        output_filename = f"{stem}_counted.jpg"
        output_path = RESULTS_DIR / output_filename
        
        if not output_path.exists():
            return JSONResponse(status_code=500, content={"error": "Failed to generate output image"})
            
        # Cleanup tasks
        if background_tasks:
            background_tasks.add_task(cleanup_file, str(input_path))
            background_tasks.add_task(cleanup_file, str(output_path))
            
        headers = {
            "X-People-Count": str(result['total']),
        }
        
        if predict_gender:
            headers["X-Boys-Count"] = str(result['boys'])
            headers["X-Girls-Count"] = str(result['girls'])
        else:
            headers["X-Boys-Count"] = "N/A"
            headers["X-Girls-Count"] = "N/A"

        return FileResponse(
            path=output_path, 
            filename=f"counted_{file.filename}.jpg",
            media_type="image/jpeg",
            headers=headers
        )
        
    except Exception as e:
        # Cleanup input if failed
        if input_path.exists():
            os.remove(input_path)
        return JSONResponse(status_code=500, content={"error": str(e)})

@app.post("/count")
async def count_people(file: UploadFile = File(...), background_tasks: BackgroundTasks = None):
    """
    Legacy endpoint: Count people + Gender (same as /predict/gender)
    """
    return await process_image_counting(file, background_tasks, predict_gender=True)

@app.post("/predict/count")
async def predict_count_only(file: UploadFile = File(...), background_tasks: BackgroundTasks = None):
    """
    Count people only (faster, no gender detection)
    """
    return await process_image_counting(file, background_tasks, predict_gender=False)

@app.post("/predict/gender")
async def predict_count_and_gender(file: UploadFile = File(...), background_tasks: BackgroundTasks = None):
    """
    Count people and detect gender
    """
    return await process_image_counting(file, background_tasks, predict_gender=True)

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
